version: "3.9"

networks:
  wordpress: 

services:
  nginx:
    container_name: wordpress-nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 8888:80
      - 4444:443
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:latest
    container_name: wordpress-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: EBLSlave##1971
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: EBLSlave##1971
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/wordpress:/var/lib/mysql
    networks:
      - wordpress

  php:
    container_name: wordpress-php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress

  wp:
    container_name: wordpress-wp
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress
